name: Verify pull request

on:
  pull_request:

jobs:
  build_image:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Build docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
